version: '3'

services:
  mysql:
    build: ./DB/ # Build from Dockerfile
    image: mysql:8.0.31-debian
    container_name: hand_motion_tracking_container
    environment:
      MYSQL_ROOT_PASSWORD: root # MySQL password setting
      MYSQL_DATABASE: hand_motion_database # MySQL Database name setting
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./DB:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
