CREATE TABLE `index_data` (
    `FingerId` INT(10) UNSIGNED NOT NULL UNIQUE,
    `IndexMeta_X` FLOAT NOT NULL DEFAULT 0,
    `IndexMeta_Y` FLOAT NOT NULL DEFAULT 0,
    `IndexMeta_Z` FLOAT NOT NULL DEFAULT 0,
    `IndexProx_X` FLOAT NOT NULL DEFAULT 0,
    `IndexProx_Y` FLOAT NOT NULL DEFAULT 0,
    `IndexProx_Z` FLOAT NOT NULL DEFAULT 0,
    `IndexInter_X` FLOAT NOT NULL DEFAULT 0,
    `IndexInter_Y` FLOAT NOT NULL DEFAULT 0,
    `IndexInter_Z` FLOAT NOT NULL DEFAULT 0,
    `IndexDist_X` FLOAT NOT NULL DEFAULT 0,
    `IndexDist_Y` FLOAT NOT NULL DEFAULT 0,
    `IndexDist_Z` FLOAT NOT NULL DEFAULT 0,
    `IndexDistRotation_R` FLOAT NOT NULL DEFAULT 0,
    `IndexDistRotation_P` FLOAT NOT NULL DEFAULT 0,
    `IndexDistRotation_Y` FLOAT NOT NULL DEFAULT 0,
    FOREIGN KEY `IndexFingerID`(`FingerId`) REFERENCES `source_data`(`Id`) ON UPDATE NO ACTION ON DELETE NO ACTION
) COLLATE = 'utf8mb4_0900_ai_ci' ENGINE = InnoDB;